[Service]
LoadCredential=tapo-username:/etc/kotibot/credentials.d/tapo-username
LoadCredential=tapo-password:/etc/kotibot/credentials.d/tapo-password
LoadCredential=tapo-camera-username:/etc/kotibot/credentials.d/tapo-camera-username
LoadCredential=tapo-camera-password:/etc/kotibot/credentials.d/tapo-camera-password
LoadCredential=firebase-service-account.json:/etc/kotibot/credentials.d/firebase-service-account.json
